name: Safesnap simulation release
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: "./yarn.lock"
      - run: yarn
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          workingDirectory: ./
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            TENDERLY_ACCESS_KEY
        env:
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
          TENDERLY_USER: gnosisguild
          TENDERLY_PROJECT: safesnap
